// Code generated by bindgen. DO NOT EDIT.
package libdemo

import (
	"unsafe"

	"github.com/ddkwork/app/bindgen/bindlib"
)

const GengoLibraryName = "libdemo"

var GengoLibrary = bindlib.NewLibrary(GengoLibraryName)

type (
	_Int128T           = any
	_Uint128T          = any
	__NSConstantString = any
	SizeT              = uint64
	_BuiltinMsVaList   = *byte
	_BuiltinVaList     = *byte
)

var __imp_hello bindlib.PreloadProc

// Gengo init function.
func init()  { __imp_hello = GengoLibrary.ImportNow("hello") }
func Hello() { bindlib.CCall0(__imp_hello.Addr()) }
